#!/bin/bash

#
# This script reads the log file for a RAMS simulation and calculates 
# the clock time to simulate a single day/sol. This information can be 
# used to estimate how long the simulation will take to run.
#
# The script requires two parameters to be entered at the command line:
# the file name and the timestep in seconds. Thus, the script is evoked
# by the following syntax:
#
# r_time wrf_log.txt 15
#
# The script would then read wrf_log.txt and calculated the clock time to
# simulate one model day using 15 seconds as the time-step in the simulation.
#
# Written by A. Soto
# 2014-02-03
#


tstep=$2

grep "TIMESTEP #" $1 | awk -v tstep="$tstep" 'BEGIN{t=0;c=0}{t=t+$13*10;c=c+1}END{print "\t total count \t|\t total time (min) \t |\t mean time \t |\t min for 1 Sim Day " ;print " \t" c " \t\t| \t " t/60 "\t\t |\t " t/c "\t |\t  " (t/c)*(6/tstep)*60*24/60}'
