#!/bin/bash

# Usage: tar_dir directory_name
# If directory name does not already have a tar version, then make a
# tarred and zipped version.

for i in "$@"
 do
     #echo "$i"
     if [[ $i != *.tar* ]]; then
        echo "Tarring $i"
#        tar czf "$i.tar.gz" "$i"
        tar -czf - "$i" | (pv -p --timer --rate --bytes > "$i.tar.gz")
        echo "Finished tarring $i"
     fi
 done
