#!/bin/bash

# Usage: tar_dir directory_name
# If directory name does not already have a tar version, then make a
# tarred and zipped version.

for i in "$@"
 do
     #echo "$i"
     if [[ $i != *.tar* ]]; then
        echo "Tarring $i"
        tar czvf "$i.tar.gz" "$i"
        echo "Finished tarring $i"
     fi
 done
