#!/bin/bash

#
# This script concatenates the wrfout files and creates an
# analysis directory that contains the concatenated file.
# The number, nn, used in the call is the number for the 
# titan paper directory.
#
# tcat nn
#
# This script is just for the titan paper simulations.


dirname='titan_paper-'
nameroot='paper-'
namenumber=$1
aname='_analysis'

currdir=`pwd`;
#echo "test $currdir/$dirname$namenumber"

# Check for an analysis directory; create one if necessary.
if test ! -d "$currdir/$dirname$namenumber$aname"; then
   echo "Creating $currdir/$dirname$namenumber$aname"
   mkdir "$currdir/$dirname$namenumber$aname";
fi

echo "Concatenating the wrfout files."
ncrcat -o $currdir/$dirname$namenumber$aname/$dirname$namenumber.nc $currdir/$dirname$namenumber/wrfout_d01_*
echo "Done."
echo ""
