#!/bin/bash

# Usage: untar_dir tar_filename
# Untar and unzip the zipped tar file. This shows a progress bar.

for i in "$@"
 do
     #echo "$i"
     #if [[ $i != *.tar* ]]; then
        echo "Untarring $i"
#        tar xzf "$i.tar.gz" "$i"
#        tar -xzf - | (pv -p --timer --rate --bytes > "$i")
         pv -p --timer --rate --bytes $i | tar -xzf - 
        echo "Finished untarring $i"
     #fi
 done
