#!/bin/bash

# This script cleans up a planetWRF output folder. RSL files are placed
# in their own directory, restart files are placed in their own directory,
# wrfout* files are placed in their own directory, etc.

# Distance ourselves (a tiny bit) from any screen litter:
echo;

# Determine fully-qualified filesystem location where this script was
# executed from:
curr_dir=`pwd`;


###
### RSL files
### 

# Check for an rsl_files directory; create one if necessary. 
if test ! -d "$curr_dir/rsl_files"; then
   mkdir "$curr_dir/rsl_files";
fi

# Move the RSL files into the rsl_files directory
if ls $curr_dir/rsl.* 1> /dev/null 2>&1; then
    mv rsl.* $curr_dir/rsl_files/.
    echo "rsl files have been moved into the rsl_files directory"
else
    echo "rsl files do not exist at this level"
fi


###
### WRF Restart files
### 

# Check for a restart directory; create one if necessary. 
if test ! -d "$curr_dir/wrf_restarts"; then
   mkdir "$curr_dir/wrf_restarts";
fi

# Move the restart files into the wrf_restarts directory
if ls $curr_dir/wrfrst* 1> /dev/null 2>&1; then
    mv wrfrst* $curr_dir/wrf_restarts/.
    echo "WRF restart files have been moved into the wrf_restarts directory"
else
    echo "WRF restart files do not exist at this level"
fi

###
### WRF Out files and namelist.input
### 

# Check for a WRF out directory; create one if necessary. 
if test ! -d "$curr_dir/wrf_out"; then
   mkdir "$curr_dir/wrf_out";
fi

# Move the WRF Out files into the wrf_out directory
if ls $curr_dir/wrfout* 1> /dev/null 2>&1; then
    mv wrfout* $curr_dir/wrf_out/.
    echo "WRF out files have been moved into the wrf_out directory"
else
    echo "WRF out files do not exist at this level"
fi

# Copy the namelist file to the wrfout directory, for posterity.
if ls $curr_dir/namelist.input 1> /dev/null 2>&1; then
    cp namelist.input $curr_dir/wrf_out/.
    echo "The namelist.input has been copied into the wrf_out directory"
else
    echo "The namelist.input file does not exist at this level"
fi


###
### Auxiliary History files
### 

# Check for a WRF Auxiliary History (auxhist) directory; create one if necessary. 
if test ! -d "$curr_dir/auxhist"; then
   mkdir "$curr_dir/auxhist";
fi

# Move the auxhist files into the auxhist directory
if ls $curr_dir/auxhist*_d* 1> /dev/null 2>&1; then
    mv auxhist*_d* $curr_dir/auxhist/.
    echo "Auxiliary History files have been moved into the auxhist directory"
else
    echo "Auxiliary History files do not exist at this level"
fi


echo;
