#!/bin/csh

# Makes a copy of the WRF run directory without copying NetCDF files
# and other auxiliary files. This is a useful step if you are running
# another simulation with the same code by a different set of 
# parameters. With this script, you can quickly set up a new directory 
# that matches the old one. 

# You need to run the wcu script before thie one. wrf_dircopy_nodata
# assumes that your data has already been organized by the wcu script.

# Usage: wrf_dircopy_nodata source_folder destination_folder
# $1 is the source folder and $2 is the destination folder
rsync -av --progress $1/. $2/. --exclude wrf_restarts --exclude wrf_out --exclude rsl_files --exclude auxhist
